<?php

namespace App\Traits;

use App\Models\Permission;
use App\Models\Role;

trait PermissionsHandler
{
    // $role->givePermissionTo("books", "1111");
    public function givePermissionTo(string $permissionName, string $actions)
    {
        $permission = Permission::where('name', $permissionName)->first();

        $this->permissions()->syncWithoutDetaching([$permission["id"] => ['active_actions' => $actions]]);

        return $this;
    }

    // $user->assignRole("crud")
    public function assignRole(string $roleName, string $extinct = null) {
        $role = Role::where('name', $roleName)->first();

        $this->roles()->syncWithoutDetaching([$role["id"] => ['extinct' => $extinct]]);

        return $this;
    }
    
    // $user->assignPermission("books", "1111", "martes")
    // $user->assignPermission("books", "1101")
    // $user->assignPermission("books", "1011")
    // $user->assignPermission("books", "0111")
    // $user->assignPermission("books", "0011")
    // $user->assignPermission("books", "0001")
    // $user->assignPermission("books", "1000")
    // $user->assignPermission("users", "1111")
    // $user->assignPermission("users", "1101")
    // $user->assignPermission("users", "1011")
    // $user->assignPermission("users", "0111")
    // $user->assignPermission("users", "0011")
    // $user->assignPermission("users", "0001")
    // $user->assignPermission("users", "1000")
    public function assignPermission(string $permissionId, string $extinct = null) {
        $role = SpecialPermission::create([
            'name' => Str::random(10),
            'description' => 'CUSTOM ROLE GENERATED BY BACKEND',
            'extict' => $extinct
        ]);

        $role->permissions()->syncWithoutDetaching([$permissionId]);

        $this->assignRole($roleName);

        return $this;
    }
}